# Generated by Django 4.2.13 on 2024-05-29 06:17

from django.db import migrations
import shared.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_emptypage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('richtext', wagtail.blocks.RichTextBlock()), ('slider_page', wagtail.blocks.StructBlock([('type', wagtail.blocks.ChoiceBlock(choices=[('high', 'high'), ('small', 'small')])), ('pages', wagtail.blocks.ListBlock(shared.blocks.CardBlock(), max_num=5, min_num=1))])), ('table_page', wagtail.blocks.StructBlock([('count_column', wagtail.blocks.IntegerBlock(label='Кол-во столбцов', max_value=5, min_value=1, required=True)), ('count_row', wagtail.blocks.IntegerBlock(label='Кол-во строк', max_value=5, min_value=1, required=True)), ('pages', wagtail.blocks.ListBlock(shared.blocks.CardBlock(), min_num=1))]))], blank=True, null=True, verbose_name='Содержимое'),
        ),
    ]
