# Generated by Django 5.0.6 on 2024-05-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='text_footer',
            field=models.TextField(blank=True, null=True, verbose_name='Текст в подвале'),
        ),
    ]
