# Generated by Django 5.0.6 on 2024-05-23 19:04

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_alter_menu_options_sitesettings_text_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='text_footer',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Текст в подвале'),
        ),
    ]
