# Generated by Django 5.0.6 on 2024-05-25 08:06

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


def setup_category(apps, schema_editor):
    article_category = apps.get_model('blog_app', 'CategoryArticle')
    article_category.objects.create(title="Спорт")
    article_category.objects.create(title="Саморазвитие")
    article_category.objects.create(title="Технологии / Программирование")

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0093_uploadedfile'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория статьи',
                'verbose_name_plural': 'Категории статей',
            },
        ),
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('content', wagtail.fields.StreamField([('richtext', wagtail.blocks.RichTextBlock())], blank=True, null=True)),
                ('image_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image')),
                ('category', models.ManyToManyField(blank=True, null=True, to='blog_app.categoryarticle', verbose_name='Категории статьи')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RunPython(setup_category),
    ]
