# Generated by Django 5.0.6 on 2024-05-26 10:46

import shared.blocks
import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_articlepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='content',
            field=wagtail.fields.StreamField([('richtext', wagtail.blocks.RichTextBlock()), ('slider_image', shared.blocks.SliderImageBlock())], blank=True, null=True),
        ),
    ]
