# Generated by Django 5.0.6 on 2024-05-26 18:29

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_articlepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='category',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, null=True, to='blog_app.categoryarticle', verbose_name='Категории статьи'),
        ),
    ]
