# Generated by Django 5.0.6 on 2024-06-01 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_articlelistpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_items', models.JSONField(blank=True, null=True, verbose_name='Выделенные элементы')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Емейл отправителя')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Текст замечания')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_app.articlepage')),
            ],
            options={
                'verbose_name': 'Замечание пользователя',
                'verbose_name_plural': 'Замечания пользователей',
            },
        ),
    ]
