# Generated by Django 5.0.6 on 2024-06-03 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_alter_articlepage_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLikesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField(null=True, verbose_name='Адрес пользователя')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_app.articlepage')),
            ],
            options={
                'verbose_name': 'Лайки пользователей',
            },
        ),
    ]
