# Generated by Django 5.0.6 on 2024-06-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_userlikesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlikesmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
